/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
var layerMetadata = [{
        name: "Case Studies",
        shortDescription: "Case Studies",
        longDescription: "This layer serves as an inventory of case studies and reports that were presented at previous EORI sponsored workshops and conferences.",
        metaURL: "<a href='http://www.uwyo.edu/eori/about/' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.uwyo.edu/eori/about/' target='_blank'>Additional Information</a>"}, 
     {        
        name: "Gas EOR Targets",
        shortDescription: "Gas EOR Targets",
         longDescription: "This layer serves as an inventory of fields that are amenable to CO2-EOR for tertiary recovery and includes active CO2-EOR projects.",
        detailsURL: "<a href='http://www.uwyo.edu/eori/about/' target='_blank'>Additional Information</a>"},    
    {       
        name: "Cored Wells",
        shortDescription: "Cored Wells",
        longDescription: "This layer shows the location and geologic formation of cored wells. This information was provided by the Wyoming Oil and Gas Conservation Commission.",
        metaURL:"<a href='http://www.uwyo.edu/eori/about/' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.uwyo.edu/eori/about/' target='_blank'>Additional Information</a>"}, 
    {
        name: "Drill Stem Tests",
        shortDescription: "Drill Stem Tests",
        longDescription: "This layer shows the location and comments of reported drill stem tests. This information was provided by the Wyoming Oil and Gas Conservation Commission.",
        metaURL:"<a href='http://www.uwyo.edu/eori/about/' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.uwyo.edu/eori/about/' target='_blank'>Additional Information</a>"}, 
    {
         name: "Well Perforations",
        shortDescription: "Well Perforations",
        longDescription: "This layer shows the location of wells with perforations, depths, and producing geologic formation. Information used to create this layer was compiled by the Enhanced Oil Recovery Institute from data provided by the Wyoming Oil and Gas Conservation Commission.",
        metaURL:"<a href='http://www.uwyo.edu/eori/about/' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.uwyo.edu/eori/about/' target='_blank'>Additional Information</a>"}, 
    {
        name: "Well Locations",
        shortDescription: "Well Locations",
        longDescription: "This layer shows the location of oil and gas wells.  This layer was compiled by the Enhanced Oil Recovery Institute from the Wyoming Oil and Gas Conservation Commission downloadable well header files.",
        metaURL:"<a href='http://www.uwyo.edu/eori/about/' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.uwyo.edu/eori/about/' target='_blank'>Additional Information</a>"}, 
    {
        name: "Core Analysis",
        shortDescription: "Core Analysis",
        longDescription: "This layer shows the locations of wells with digitally available core analysis. This layer is being compiled by the Enhanced Oil Recovery Institute from the Wyoming Oil and Gas Conservation Commission downloadable core analysis pdf files. This layer is associated with on the fly charts showing porosity, permeability, and oil saturation.",
        metaURL:"<a href='http://www.uwyo.edu/eori/about/' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.uwyo.edu/eori/about/' target='_blank'>Additional Information</a>"}, 
    {
        name: "Well Deviations",
        shortDescription: "Well Deviations",
        longDescription: "This layer shows the location and orientation of deviated and horizontal wells. This layer was compiled by the Enhanced Oil Recovery Institute from the Wyoming Oil and Gas Conservation Commission downloadable well header files.",
        metaURL:"<a href='http://www.uwyo.edu/eori/about/' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.uwyo.edu/eori/about/' target='_blank'>Additional Information</a>"}, 
    {
        name: "CO2 Miscibility",
        shortDescription: "CO2 Miscibility",
        longDescription: "This layer shows the locations of oil fields that are suitable for CO2-EOR injection projects. Information used to create this layer was compiled by the Enhanced Oil Recovery Institute from the Wyoming Oil and Gas Conservation Commission, Wyoming Geological Association, and the US Department of Energy National Energy Technology Laboratory.",
        metaURL: "<a href='http://www.uwyo.edu/eori/about/' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.uwyo.edu/eori/about/' target='_blank'>Additional Information</a>"}, 
    {
        name: "Field Locations",
        shortDescription: "Field Locations",
        longDescription: "This layer represents the general location and name of oil and gas fields.",
        metaURL: "<a href='http://www.uwyo.edu/eori/about/' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.uwyo.edu/eori/about/' target='_blank'>Additional Information</a>"}, 
    {
        name: "Field Areas",
        shortDescription: "Field Areas",
        longDescription: "This layer represents the general distributional area of wells associated by a common oil and gas Field Name. This layer serves as an update to the 2012 Wyoming State Geological Survey Oil and Gas layer by De Bruin. The purpose of a field area data set is to represent the distribution of wells that share a common field name. The field area layer is by no means meant to assess acreage, production, or resources and reserves. This layer was created by the Enhanced Oil Recovery Institute.",
        metaURL: "<a href='http://www.uwyo.edu/eori/about/' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.uwyo.edu/eori/about/' target='_blank'>Additional Information</a>"}, 
    {
        name: "OGCC Reported Production",
         shortDescription: "OGCC Reported Production",
        longDescription: "This layer represents the general distributional area of wells associated by a common oil and gas Field Name and is associated with on the fly charts showing annual production and injection volumes. Production and injection data was compiled from the Wyoming Oil and Gas Conservation Commission.",
        metaURL: "<a href='http://www.uwyo.edu/eori/about/' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.uwyo.edu/eori/about/' target='_blank'>Additional Information</a>"}, 
    {
        
        name: "Permits",
        shortDescription: "Permits",
        longDescription: "Permits to drill.",
        metaURL: "<a href='http://wogccms.state.wy.us/arcgis/rest/services/WOGCC/Units/MapServer/1' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://wogcc.state.wy.us/' target='_blank'>Additional Information</a>"}, 
    {
        name: "Conventional",
         shortDescription: "Conventional",
        longDescription: "Conventional oil and gas wells",
        metaURL: "<a href='http://wogccms.state.wy.us/arcgis/rest/services/WOGCC/Units/MapServer/2' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://wogcc.state.wy.us/' target='_blank'>Additional Information</a>"}, 
    {
        name: "CoalBed",
         shortDescription: "CoalBed",
        longDescription: "CoalBed methane wells.",
        metaURL: "<a href='http://wogccms.state.wy.us/arcgis/rest/services/WOGCC/Units/MapServer/3' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://wogcc.state.wy.us/' target='_blank'>Additional Information</a>"}, 
    {
        name: "InjectionWells",
         shortDescription: "Injection Wells",
        longDescription: "Injection or Disposal Well shall mean any well used for the injection of air, gas, water or other substance into any underground stratum",
        metaURL: "<a href='http://wogccms.state.wy.us/arcgis/rest/services/WOGCC/Units/MapServer/4' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://wogcc.state.wy.us/' target='_blank'>Additional Information</a>"}, 
    {
        name: "DisposalWells",
         shortDescription: "Disposal Wells",
        longDescription: "A commercial disposal well or commercial water retention pit",
        metaURL: "<a href='http://wogccms.state.wy.us/arcgis/rest/services/WOGCC/Units/MapServer/5' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://wogcc.state.wy.us/' target='_blank'>Additional Information</a>"}, 
    {
        name: "Units",
         shortDescription: "Metadata coming soon.",
        longDescription: "Metadata coming soon.",
        metaURL: "<a href='http://wogccms.state.wy.us/arcgis/rest/services/WOGCC/Units/MapServer/7' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://wogcc.state.wy.us/' target='_blank'>Additional Information</a>"}, 
    {
        name: "Horizontal",
         shortDescription: "Metadata coming soon.",
        longDescription: "Metadata coming soon.",
        metaURL: "<a href='http://wogccms.state.wy.us/arcgis/rest/services/WOGCC/Units/MapServer/9' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://wogcc.state.wy.us/' target='_blank'>Additional Information</a>"}, 
  
    {
        name: "Water Analysis",
         shortDescription: "Metadata coming soon.",
        longDescription: "Metadata coming soon.",
        metaURL: "<a href='http://wogccms.state.wy.us/arcgis/rest/services/WOGCC/Units/MapServer/12' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://wogcc.state.wy.us/' target='_blank'>Additional Information</a>"}, 
  
    {
        name: "Stimulation",
         shortDescription: "Metadata coming soon.",
        longDescription: "Metadata coming soon.",
        metaURL: "<a href='http://wogccms.state.wy.us/arcgis/rest/services/WOGCC/Units/MapServer/14' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://wogcc.state.wy.us/' target='_blank'>Additional Information</a>"}, 
  
    {
        name: "City & Town Boundaries",
        shortDescription: "Municipal boundaries for cities and towns in Wyoming.",
        longDescription: "This dataset represents the simple municipal outer boundaries cities and towns in Wyoming.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid=%7B78909434-F736-4F8C-954F-3F97D0A4625E%7D' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://revenue.wyo.gov/' target='_blank'>Additional Information</a>"}, 
    {
        name: "County Boundaries",
        shortDescription: "County Boundaries for Wyoming at 1:24,000",
        longDescription: "Wyoming counties at 1:24,000 scale.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/rest/document?id=%7BCF6F91EF-F791-4E8A-9C5A-3880579FB40F%7D' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.blm.gov/wy/st/en/resources/public_room/gis/datagis/state/county.html' target='_blank'>Additional Information</a>"},
    {
        name: "State Parks",
        shortDescription: "Simple outer boundaries of Wyoming's state parks and historic places.",
        longDescription: "This dataset represents the Simple outer boundaries of Wyoming's state parks and historic places for Wyoming.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={C05065B2-7BA6-4CED-A092-9D1898581982}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://wyoparks.state.wy.us/' target='_blank'>Additional Information</a>"}, 
    {
        name: "Wind River Reservation",
        shortDescription: "Simple outer boundary of the Wind River Reservation.",
        longDescription: "This dataset represents the simple outer boundary of the Wind River Reservation.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={BC1EA9A6-28AB-4389-8327-13F14A21D0AF}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://en.wikipedia.org/wiki/Wind_River_Indian_Reservation' target='_blank'>Additional Information</a>"}, 
    {
        name: "National Parks and Monuments",
        shortDescription: "Simple outer boundaries of the National Parks and Monuments in Wyoming.",
        longDescription: "Simple outer boundaries of the National Parks and Monuments in Wyoming.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={DA94E278-178A-47CE-BCFE-E851151BAC67}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.nps.gov/state/wy/index.htm?program=all' target='_blank'>Additional Information</a>"}, 
    {
        name: "National Recreation Areas",
        shortDescription: "Simple outer boundaries of the National Recreation Areas in Wyoming.",
        longDescription: "Simple outer boundaries of the Recreation Areas in Wyoming.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={91B05033-F1E3-4F1D-84BC-9E63F59BC19C}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.nps.gov/state/wy/list.htm?program=parks' target='_blank'>Additional Information</a>"}, 
    {
        name: "National Wildlife Refuges",
        shortDescription: "Simple outer boundaries of the National Wildlife Refuges in Wyoming.",
        longDescription: "Simple outer boundaries of the National Wildlife Refuges in Wyoming.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={53138F60-C27C-41EE-80EB-49013189B3DE}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.fws.gov/mountain-prairie/refuges/wy/' target='_blank'>Additional Information</a>"},
    {
        name: "National Forests",
        shortDescription: "Simple outer boundaries of the National Forests in Wyoming.",
        longDescription: "Simple outer boundaries of the National Forests in Wyoming.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={BA79B3BE-6374-49A3-9ACC-961608D2AAAD}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.fs.fed.us/recreation/map/state_list.shtml#W' target='_blank'>Additional Information</a>"},
    {
        name: "Wilderness Areas",
        shortDescription: "Simple outer boundaries of the National Forest Wilderness Areas in Wyoming.",
        longDescription: "Simple outer boundaries of the National Forest Wilderness Areas in Wyoming.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={13CD1029-F4F2-4E58-88FD-CEE90BCC40AC}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.fs.fed.us/r2/recreation/map/wyoming/html-current/080708/hi-speed%20map/wyoming-hi-speed-index.shtml' target='_blank'>Additional Information</a>"},
    {
        name: "Wilderness Study Areas",
        shortDescription: "Simple outer boundaries of the Bureau of Land Management Wilderness Study Areas in Wyoming.",
        longDescription: "Simple outer boundaries of the Bureau of Land Management Wilderness Study Areas in Wyoming.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={2293C197-215D-47DD-8AD1-D84C656F667E}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.blm.gov/wy/st/en/programs/nlcs/wsa.html' target='_blank'>Additional Information</a>"}, 
    {
        name: "Areas of Critical Environmental Concern",
        shortDescription: "Simple outer boundaries of the Bureau of Land Management Areas of Critical Environmental Concern in Wyoming.",
        longDescription: "Simple outer boundaries of the Bureau of Land Management Areas of Critical Environmental Concern in Wyoming.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={5E085C1E-0BDB-4A25-B62C-3EE23A6BFB58}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.blm.gov/ut/st/en/fo/st__george/blm_special_areas/areas_of_critical.html' target='_blank'>Additional Information</a>"}, 
    {
        name: "Unique and Irreplaceable Lands",
        shortDescription: "Boundaries of Unique and Irreplaceable Lands in Wyoming.",
        longDescription: "Simple outer boundaries of Unique and Irreplaceable Lands in Wyoming.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={A08407A5-A06C-4757-95FD-90C7DA94AA6D}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.wsgs.uwyo.edu/public-info/news/2010/Jan15_2010.aspx' target='_blank'>Additional Information</a>"},
    {
        name: "Townships",
        shortDescription: "Public Land Survey System (PLSS) Township and Range in Wyoming.",
        longDescription: "The Public Land Survey System (PLSS) is a way of subdividing and describing land in the United States. All lands in the public domain are subject to subdivision by this rectangular system of surveys, which is regulated by the U.S. Department of the Interior, Bureau of Land Management (BLM). The PLSS typically divides land into 6-mile-square townships. Townships are subdivided into 36 one-mile- square sections. Sections can be further subdivided into quarter sections, quarter-quarter sections, or irregular government lots.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={0801F02E-A242-41BC-91D0-C01BE3AEDCA8}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://nationalatlas.gov/articles/boundaries/a_plss.html' target='_blank'>Additional Information</a>"},
    {
        name: "Sections",
        shortDescription: "Public Land Survey System (PLSS) Sections in Wyoming.",
        longDescription: "The Public Land Survey System (PLSS) is a way of subdividing and describing land in the United States. All lands in the public domain are subject to subdivision by this rectangular system of surveys, which is regulated by the U.S. Department of the Interior, Bureau of Land Management (BLM). The PLSS typically divides land into 6-mile-square townships. Townships are subdivided into 36 one-mile- square sections. Sections can be further subdivided into quarter sections, quarter-quarter sections, or irregular government lots.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={0801F02E-A242-41BC-91D0-C01BE3AEDCA8}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://nationalatlas.gov/articles/boundaries/a_plss.html' target='_blank'>Additional Information</a>"},
    {
        name: "Quarter Sections",
        shortDescription: "Public Land Survey System (PLSS) Quarter Sections in Wyoming.",
        longDescription: "The Public Land Survey System (PLSS) is a way of subdividing and describing land in the United States. All lands in the public domain are subject to subdivision by this rectangular system of surveys, which is regulated by the U.S. Department of the Interior, Bureau of Land Management (BLM). The PLSS typically divides land into 6-mile-square townships. Townships are subdivided into 36 one-mile- square sections. Sections can be further subdivided into quarter sections, quarter-quarter sections, or irregular government lots.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={0801F02E-A242-41BC-91D0-C01BE3AEDCA8}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://nationalatlas.gov/articles/boundaries/a_plss.html' target='_blank'>Additional Information</a>"},
    {
        name: "Quarter/Quarter Sections",
        shortDescription: "Public Land Survey System (PLSS) Quarter/Quarter Sections in Wyoming.",
        longDescription: "The Public Land Survey System (PLSS) is a way of subdividing and describing land in the United States. All lands in the public domain are subject to subdivision by this rectangular system of surveys, which is regulated by the U.S. Department of the Interior, Bureau of Land Management (BLM). The PLSS typically divides land into 6-mile-square townships. Townships are subdivided into 36 one-mile- square sections. Sections can be further subdivided into quarter sections, quarter-quarter sections, or irregular government lots.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={0801F02E-A242-41BC-91D0-C01BE3AEDCA8}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://nationalatlas.gov/articles/boundaries/a_plss.html' target='_blank'>Additional Information</a>"}, 
    {
        name: "Land Management",
        shortDescription: "This dataset represents surface federal and state management for Wyoming.",
        longDescription: "This dataset represents surface federal and state management for Wyoming.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={6246093C-91CE-4E80-A1D7-CADD66978203}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.blm.gov/wy/st/en/resources/public_room/gis/metadata/own.html' target='_blank'>Additional Information</a>"},
    {
        name: "Oil & Gas Wells",
        shortDescription: "Wyoming Oil and Gas Conservation Commission (WOGCC) wells.",
        longDescription: "Wyoming Oil and Gas Conservation Commission (WOGCC) wells.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={7D3DBDC4-5395-490A-8353-F3798DB688D7}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://wogcc.state.wy.us/' target='_blank'>Additional Information</a>"}, 
    {
        name: "CO2 Sources (megatons)",
        shortDescription: "Sources of CO2 emissions in Wyoming.",
        longDescription: "This dataset is compiled of data from the United States Environmental Protection Agency, Greenhouse Gas Reporting Program. They are point source locations of CO2 emissions above 25,000 tons per year, from industrial facilities.",
        metaURL: "<a href='http://www.epa.gov/ghgreporting/ghgdata/2011data.html' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://ghgdata.epa.gov/ghgp/main.do' target='_blank'>Additional Information</a>"}, 
    {
        name: "Power Generation",
        shortDescription: "Electrical power generation locations.",
        longDescription: "This dataset is compiled of data and locations for electrical generating sites in Wyoming contributing to the grid. The data is intended for scales of 1:100,000 and smaller.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={147DDD1F-F539-4897-BF68-DD00B272653A}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.wsgs.uwyo.edu/data/gis/Energy.aspx' target='_blank'>Additional Information</a>"}, 
    {
        name: "Coal Mines",
        shortDescription: "Coal mines in Wyoming.",
        longDescription: "Simple coal mine permit boundaries for Wyoming, including active mining areas, dragline transport permitted areas, areas undergoing reclamation and temporarily halted mining.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={2A480189-4F8F-4983-92BB-1FF28CF51748}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.wsgs.uwyo.edu/Research/Energy/Coal/' target='_blank'>Additional Information</a>"},
    {
        name: "Wind Turbines",
        shortDescription: "Wind turbines locations in Wyoming.",
        longDescription: "These data represent locations of wind turbines found in Wyoming.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={C7E27F34-E77C-4D0E-8F4B-4D2E1ED55807}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.usgs.gov/blogs/features/usgs_top_story/mapping-the-nations-wind-turbines/' target='_blank'>Additional Information</a>"}, 
    {
        name: "Transmission Lines",
        shortDescription: "Transmission Lines in Wyoming.",
        longDescription: "These data represent general simplified locations of Transmission Lines in Wyoming.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={44D3094E-EE68-4358-B3D3-EFBB88B377CA}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://en.wikipedia.org/wiki/Electric_power_transmission' target='_blank'>Additional Information</a>"}, 
    {
        name: "Pipelines",
        shortDescription: "Pipelines in Wyoming.",
        longDescription: "These data represent general simplified locations of pipelines in Wyoming.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={2867169F-86DE-460C-96DC-7B419D1B4D31}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.eia.gov/pub/oil_gas/natural_gas/analysis_publications/ngpipeline/index.html' target='_blank'>Additional Information</a>"},
    {
        name: "Non-irrigated Agriculture",
        shortDescription: "Non-irrigated Agriculture in Wyoming.",
        longDescription: "These data represent general simplified locations of Non-irrigated Agriculture in Wyoming.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={EA9EA309-197C-4BEC-B3EB-EA473E8B1E90}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://en.wikipedia.org/wiki/Dryland_farming' target='_blank'>Additional Information</a>"}, 
    {
        name: "Irrigated Agriculture",
        shortDescription: "Irrigated Agriculture in Wyoming.",
        longDescription: "These data represent general simplified locations of irrigated Agriculture in Wyoming.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={F438110C-FA24-47FA-A96D-7E3CDE21D6EE}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://en.wikipedia.org/wiki/Irrigation' target='_blank'>Additional Information</a>"}, 
    {
        name: "Agriculture",
        shortDescription: "Irrigated and dryland agriculture in Wyoming.",
        longDescription: "These data represent general simplified locations of irrigated Agriculture in Wyoming.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={F438110C-FA24-47FA-A96D-7E3CDE21D6EE}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://en.wikipedia.org/wiki/Irrigation' target='_blank'>Additional Information</a>"}, 
    {
        name: "Housing Development",
        shortDescription: "Housing Development in Wyoming.",
        longDescription: "These data represent U.S. Census 2010 Housing Development in Wyoming at the block level.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={63F7FE06-CA5C-4EAE-AF38-7AF2BB6F1FA5}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.census.gov/2010census/popmap/' target='_blank'>Additional Information</a>"}, 
    {
        name: "Modeled Disturbance",
        shortDescription: "Modeled Human Disturbance in Wyoming.",
        longDescription: "This dataset is a model of Human Disturbance features in Wyoming, including roads, energy infrastructure, and other features.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={56900735-B982-4428-9694-CBFA6ECA3157}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.journalconsplanning.org/2007/Volume3/JCP_V3_Copeland.pdf' target='_blank'>Additional Information</a>"}, 
    {
        name: "Wind Power Potential",
        shortDescription: "Wind Power Potential in Wyoming.",
        longDescription: "Annual average wind resource potential of the northwestern United States at a 50 meter height. These are modeled data of potential wind speeds at a 400 meter cell spatial resolution.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={D3888BB3-713A-4B67-9E54-F2E55CD0E786}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.windpoweringamerica.gov/' target='_blank'>Additional Information</a>"}, 
    {
        name: "Big Game Migration Routes",
        shortDescription: "Big game migration general routes in Wyoming.",
        longDescription: "This data set represents statewide migration corridors or routes for elk, moose, mule deer, white-tailed deer, and rocky mountain goat within the state of Wyoming.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={CD03A5A7-773A-4146-A8AA-66658A693C33}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='' target='_blank'>Additional Information</a>"}, 
    {
        name: "Big Game Crucial Ranges",
        shortDescription: "Big game migration general crucial seasonal ranges in Wyoming.",
        longDescription: "This data set represents statewide crucial seasonal range for elk, moose, mule deer, white-tailed deer, and rocky mountain goat within the state of Wyoming.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={A976EC32-6C6B-43D4-9E95-F1E451B5436A}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='' target='_blank'>Additional Information</a>"}, 
    {
        name: "Sage-Grouse Core Areas",
        shortDescription: "Sage-Grouse core areas in Wyoming.",
        longDescription: "Sage-Grouse core areas in Wyoming directed by the Governors executive order. These areas were delineated to delineate breeding and nesting habitat in Wyoming. Special consideration was given to habitat that was not already impacted by human influences (oil and gas, subdivisions, mining, wind, etc.).",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={284327E1-E75C-408B-9D8E-DCCC27AFDE45}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='' target='_blank'>Additional Information</a>"},
    {
        name: "Sage-Grouse Connectivity Areas",
        shortDescription: "Sage-Grouse population connectivity areas.",
        longDescription: "Connectivity areas were designed to connect Wyoming Sage-Grouse core populations with Montana sage-grouse populations.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={8A1BC3E0-523D-4060-8C67-A76C5AA2BDC6}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='' target='_blank'>Additional Information</a>"}, 
    {
        name: "Climate Stations",
        shortDescription: "Climate station locations in and near Wyoming",
        longDescription: "This dataset contains 4222 point locations corresponding to 136 weather station locations in or bordering Wyoming. Each of the 136 weather stations includes 31 points, with the same latitude and longitude, but representing a different year (1970-2000). Data are recorded for precipitation and temperature for each location in each year.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={FC163EB5-7674-40E2-AA28-19A67ADDCEF9}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.wrcc.dri.edu/' target='_blank'>Additional Information</a>"}, 
    {
        name: "SNOTEL (Snowpack) Stations",
        shortDescription: "SNOTEL (SNOwpack TELemetry) sites for the State of Wyoming.",
        longDescription: "The Natural Resources Conservation Service (NRCS) Wyoming Casper Office provide SNOTEL (SNOwpack TELemetry) sites data to aid with climate studies, air and water quality investigations, and resource management concerns are all served by the modern SNOTEL network. The high-elevation watershed locations and the broad coverage of the network provide important data collection opportunities to researchers, water managers, and emergency managers for natural disasters such as floods.",
        metaURL: "<a href='http://www.wcc.nrcs.usda.gov/snotel/Wyoming/wyoming.html' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.wcc.nrcs.usda.gov/snow/' target='_blank'>Additional Information</a>"}, 
    {
        name: "Average Daily Maximum Air Temperature (C)",
        shortDescription: "Annual mean of daily maximum temperature records modeled for the topagraphically diverse landscape of Wyoming.",
        longDescription: "Meteorology at the land surface affects many processes in the terrestrial biogeochemical system. Measurements of near-surface meteorological conditions are made at many locations, but we are often faced with having to perform ecosystem process simulations in areas where no meteorological measurements have been taken. In some cases it is possible to install new instrumentation for a particular study, but there are many situations where this is not a feasible solution. These problems are particularly important for simulations over large regions, where the number of simulation points is likely to be far greater than the number of observation stations. Daymet is a model that generates daily surfaces of temperature and precipitation, based on known climate station data, and extrapolated to topography of the rest of the area.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={227F4EB5-5D77-4A6C-9F97-86A1DAF4E610}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='' target='_blank'>Additional Information</a>"}, 
    {
        name: "Average Daily Minimum Air Temperature (C)",
        shortDescription: "Annual mean of daily minimum temperature records modeled for the topagraphically diverse landscape of Wyoming.",
        longDescription: "Meteorology at the land surface affects many processes in the terrestrial biogeochemical system. Measurements of near-surface meteorological conditions are made at many locations, but we are often faced with having to perform ecosystem process simulations in areas where no meteorological measurements have been taken. In some cases it is possible to install new instrumentation for a particular study, but there are many situations where this is not a feasible solution. These problems are particularly important for simulations over large regions, where the number of simulation points is likely to be far greater than the number of observation stations. Daymet is a model that generates daily surfaces of temperature and precipitation, based on known climate station data, and extrapolated to topography of the rest of the area.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={9B365400-042F-4743-8A40-A24D176EE0DD}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='' target='_blank'>Additional Information</a>"}, 
    {
        name: "Total Annual Precipitation (mm)",
        shortDescription: "Annual mean of daily precipitation records modeled for the topagraphically diverse landscape of Wyoming.",
        longDescription: "Meteorology at the land surface affects many processes in the terrestrial biogeochemical system. Measurements of near-surface meteorological conditions are made at many locations, but we are often faced with having to perform ecosystem process simulations in areas where no meteorological measurements have been taken. In some cases it is possible to install new instrumentation for a particular study, but there are many situations where this is not a feasible solution. These problems are particularly important for simulations over large regions, where the number of simulation points is likely to be far greater than the number of observation stations. Daymet is a model that generates daily surfaces of temperature and precipitation, based on known climate station data, and extrapolated to topography of the rest of the area.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={58DE3375-02C2-423D-BD88-3E3A9495B897}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='' target='_blank'>Additional Information</a>"}, 
    {
        name: "Land Cover Types",
        shortDescription: "Simple Land Cover Classifications for Wyoming.",
        longDescription: "Land cover classifications (in Wyoming, these are mostly vegetation types) at 1:100,000 scale. Attributes describe the primary Land cover type (such as conifer forest, or grass-dominated reparian). Land Cover differs from vegetation in that it includes water, permanent snow, bare ground, and human development areas. The data were developed to aid in mapping species habitat types.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={A898361F-4157-449A-A5E0-400B05341B86}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://en.wikipedia.org/wiki/Land_cover' target='_blank'>Additional Information</a>"}, 
    {
        name: "Surficial Geology",
        shortDescription: "Geologic features present on the surface of Wyoming's landscapes.",
        longDescription: "This dataset represents surficial geology of Wyoming at 1:500,000-scale. The layer contains 577 separate surficial feature (landforms) and deposit descriptions present on the surface in the state.",
         metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid=%7B6696D49C-08F9-476B-B34A-B8569171740F%7D' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.wsgs.uwyo.edu/' target='_blank'>Additional Information</a>"}, 
    {
        name: "Bedrock Geology",
        shortDescription: "Simple bedrock descriptions of rock type.",
        longDescription: "These data were developed to be viewed and used at a 1:500,000 scale or smaller (coarse scale). These very simplified geologic rock types provide a simple guide to bedrock geology of the state of Wyoming.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid=%7BFD45E832-9DE1-4B65-9262-2DBBC1047348%7D' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.wsgs.uwyo.edu/' target='_blank'>Additional Information</a>"}, 
    {
        name: "Elevation",
        shortDescription: "Elevation of Wyoming",
        longDescription: "A DEM (Digital Elevation Model) represents an elevation value for each 90 meter cell. Raster datasets are like a digital photograph, represented as rows of pixels, where each pixel has a value. In this case, a measure of elevation.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={91D8060D-7A81-427A-AC09-FBE477CAC8EE}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://en.wikipedia.org/wiki/Elevation' target='_blank'>Additional Information</a>"},
    {
        name: "Water Gaging Stations",
        shortDescription: "USGS gauging stations to monitor stream flow on waterways across the US.",
        longDescription: "The United States Geological Survey (USGS) maintains stream sites with real-time or recent surface-water, groundwater, or water-quality data. These stream data include information such as discharge (in cubic feet per second) daily, monthly and annually, providing up to the minute information on river flow across the US.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={773D65DF-2CE2-458C-90A7-D928EEFDA9A4}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://waterdata.usgs.gov/nwis' target='_blank'>Additional Information</a>"},
    {
        name: "Level 4 Watersheds",
        shortDescription: "Level 4 Watersheds (8 digit Hydrologic Unit Boundaries) are subbasins of larger watershed regions.",
        longDescription: "This data set is a complete digital hydrologic unit boundary layer to the Watershed (8-digit) 4th level for the state of Wyoming. The Watershed and Subwatershed hydrologic unit boundaries provide a uniquely identified and uniform method of subdividing large drainage areas.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={943FCBC9-7E26-41BF-9FE2-182AEA019B0B}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://en.wikipedia.org/wiki/Hydrological_code#United_States' target='_blank'>Additional Information</a>"},
    {
        name: "Level 5 Watersheds",
        shortDescription: "Level 5 Watersheds (10 digit Hydrologic Unit Boundaries) are subbasins of larger watershed regions.",
        longDescription: "This data set is a complete digital hydrologic unit boundary layer to the Watershed (10-digit) 5th level for the state of Wyoming. The Watershed and Subwatershed hydrologic unit boundaries provide a uniquely identified and uniform method of subdividing large drainage areas.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={DE81A9D7-3765-4292-A5AF-EDED3B2B218E}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://en.wikipedia.org/wiki/Hydrological_code#United_States' target='_blank'>Additional Information</a>"}, 
    {
        name: "Level 6 Watersheds",
        shortDescription: "Level 6 Watersheds (12 digit Hydrologic Unit Boundaries) are subbasins of larger watershed regions.",
        longDescription: "This data set is a complete digital hydrologic unit boundary layer to the Watershed (12-digit) 6th level for the state of Wyoming. The Watershed and Subwatershed hydrologic unit boundaries provide a uniquely identified and uniform method of subdividing large drainage areas.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={FB684063-ABA5-4429-8659-DA9DC945EF22}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://en.wikipedia.org/wiki/Hydrological_code#United_States' target='_blank'>Additional Information</a>"}, 
    {
        name: "Impaired Streams (DEQ)",
        shortDescription: "Impaired water quality, assessed by the water quality division of the Wyoming Department of Environmental Quality (DEQ) and posted to the Environmental Protection Agency.",
        longDescription: "The state of Wyoming�s Department of Environmental Quality regulates the surface water standards. The nine water uses managed for by the Wyoming Surface Water Classification List: drinking water, fisheries, aquatic life other than fish, fish consumption, recreation, wildlife, agriculture, industry, and scenic value (refer to the standards document for descriptions).",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={79E74E2B-A9A8-4F60-8861-5A1C193629F8}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://deq.state.wy.us/wqd/watershed/surfacestandards/Downloads/Standards/WyomingMethods_13_0352.pdf' target='_blank'>Additional Information</a>"}, 
    {
        name: "Impaired Lakes (DEQ)",
        shortDescription: "Impaired water quality, assessed by the water quality division of the Wyoming Department of Environmental Quality (DEQ) and posted to the Environmental Protection Agency.",
        longDescription: "The state of Wyoming�s Department of Environmental Quality regulates the surface water standards. The nine water uses managed for by the Wyoming Surface Water Classification List: drinking water, fisheries, aquatic life other than fish, fish consumption, recreation, wildlife, agriculture, industry, and scenic value (refer to the standards document for descriptions).",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={79E74E2B-A9A8-4F60-8861-5A1C193629F8}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://deq.state.wy.us/wqd/watershed/surfacestandards/Downloads/Standards/WyomingMethods_13_0352.pdf' target='_blank'>Additional Information</a>"}, 
    {
        name: "Wetlands",
        shortDescription: "Wetland classifications for Wyoming.",
        longDescription: "This wetlands of Wyoming data set represents the extent, approximate location and type of wetlands, riparian areas and aquatic habitats in Wyoming. The wetlands are classified by the U.S. Fish and Wildlife Service into 6 categories, including freshwater emergent wetland, freshwater emergent wetland, freshwater forested/shrub wetland, lake, riverine, and other. Additional information on wetlands can be found at the U.S. Fish and Wildlife Service.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={2A922B30-2BCD-454E-BC36-0B0B9DB79E18}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.fws.gov/wetlands/Documents/classwet/index.html' target='_blank'>Additional Information</a>"},
    {
        name: "National Wild and Scenic Rivers",
        shortDescription: "National Wild and Scenic Rivers in Wyoming.",
        longDescription: "The National Wild and Scenic Rivers System was created by Congress in 1968 (Public Law 90-542; 16 U.S.C. 1271 et seq.) to preserve certain rivers with outstanding natural, cultural, and recreational values in a free-flowing condition for the enjoyment of present and future generations.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={38851ECB-C9E9-4C8B-80DB-EE2CF2400330}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='http://www.rivers.gov/wsr-act.php' target='_blank'>Additional Information</a>"}, 
    {
        name: "Depth to Initial Groundwater",
        shortDescription: "Approximate modeled depth to initial ground water measured in feet.",
        longDescription: "This data represents a depiction of the Depth to Initial Ground Water for the state of Wyoming (excluding Yellowstone National Park) at a 100 meter cell resolution, 1:100,000 scale. These are modeled data from existing water well data available in Wyoming in 1997.",
        metaURL: "<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid={05FAAD38-8AD4-4B3B-9E02-421F7171FE28}' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='' target='_blank'>Additional Information</a>"},
    {
        name: "PRISM 30yr max temperature (F)",
        shortDescription: "Annual mean of daily maximum temperature records modeled for the topagraphically diverse landscape of Wyoming.",
        longDescription: "Meteorology at the land surface affects many processes in the terrestrial biogeochemical system. Measurements of near-surface meteorological conditions are made at many locations, but we are often faced with having to perform ecosystem process simulations in areas where no meteorological measurements have been taken. In some cases it is possible to install new instrumentation for a particular study, but there are many situations where this is not a feasible solution. These problems are particularly important for simulations over large regions, where the number of simulation points is likely to be far greater than the number of observation stations. Daymet is a model that generates daily surfaces of temperature and precipitation, based on known climate station data, and extrapolated to topography of the rest of the area.",
        metaURL: "<a href=javascript:popitup('http://explorer.geospatialhub.org/geoportal/rest/document?id=%7BCC528E86-58A6-4441-BB6A-2A38DBF6B741%7D') target='_blank'>Full Metadata Record</a>",
         detailsURL: "<a href=javascript:popitup('http://www.prism.oregonstate.edu/normals/') target='_blank'>Additional Information</a>"},
    {
        name: "PRISM 30yr min temperature (F)",
        shortDescription: "Annual mean of daily minimum temperature records modeled for the topagraphically diverse landscape of Wyoming.",
        longDescription: "Meteorology at the land surface affects many processes in the terrestrial biogeochemical system. Measurements of near-surface meteorological conditions are made at many locations, but we are often faced with having to perform ecosystem process simulations in areas where no meteorological measurements have been taken. In some cases it is possible to install new instrumentation for a particular study, but there are many situations where this is not a feasible solution. These problems are particularly important for simulations over large regions, where the number of simulation points is likely to be far greater than the number of observation stations. Daymet is a model that generates daily surfaces of temperature and precipitation, based on known climate station data, and extrapolated to topography of the rest of the area.",
        metaURL: "<a href=javascript:popitup('http://explorer.geospatialhub.org/geoportal/rest/document?id=%7BCC528E86-58A6-4441-BB6A-2A38DBF6B741%7D') target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href=javascript:popitup('http://www.prism.oregonstate.edu/normals/') target='_blank'>Additional Information</a>"},
    {
        name: "PRISM 30yr mean temperature (F)",
        shortDescription: "Annual mean of daily mean temperature records modeled for the topagraphically diverse landscape of Wyoming.",
        longDescription: "Meteorology at the land surface affects many processes in the terrestrial biogeochemical system. Measurements of near-surface meteorological conditions are made at many locations, but we are often faced with having to perform ecosystem process simulations in areas where no meteorological measurements have been taken. In some cases it is possible to install new instrumentation for a particular study, but there are many situations where this is not a feasible solution. These problems are particularly important for simulations over large regions, where the number of simulation points is likely to be far greater than the number of observation stations. Daymet is a model that generates daily surfaces of temperature and precipitation, based on known climate station data, and extrapolated to topography of the rest of the area.",
        metaURL: "<a href=javascript:popitup('http://explorer.geospatialhub.org/geoportal/rest/document?id=%7BCC528E86-58A6-4441-BB6A-2A38DBF6B741%7D') target='_blank'>Full Metadata Record</a>",
         detailsURL: "<a href=javascript:popitup('http://www.prism.oregonstate.edu/normals/') target='_blank'>Additional Information</a>"},
    {
        name: "PRISM 30yr precipitation (in)",
        shortDescription: "Annual mean of daily precipitation records modeled for the topagraphically diverse landscape of Wyoming.",
        longDescription: "Meteorology at the land surface affects many processes in the terrestrial biogeochemical system. Measurements of near-surface meteorological conditions are made at many locations, but we are often faced with having to perform ecosystem process simulations in areas where no meteorological measurements have been taken. In some cases it is possible to install new instrumentation for a particular study, but there are many situations where this is not a feasible solution. These problems are particularly important for simulations over large regions, where the number of simulation points is likely to be far greater than the number of observation stations. Daymet is a model that generates daily surfaces of temperature and precipitation, based on known climate station data, and extrapolated to topography of the rest of the area.",
        metaURL: "<a href=javascript:popitup('http://explorer.geospatialhub.org/geoportal/rest/document?id=%7BCC528E86-58A6-4441-BB6A-2A38DBF6B741%7D') target='_blank'>Full Metadata Record</a>",
         detailsURL: "<a href=javascript:popitup('http://www.prism.oregonstate.edu/normals/') target='_blank'>Additional Information</a>"},
      {
        name: "Carbon Dioxide",
        shortDescription: "This dataset consists of a statewide GIS database of major oil, gas, carbon dioxide, water, and product pipelines for the state of Wyoming.",
        longDescription: "This dataset consists of a statewide GIS database of major oil, gas, carbon dioxide, water, and product pipelines for the state of Wyoming. It was produced by the Wyoming Pipeline Authority with an initial contribution by the Wyoming State Geological Survey and the help of various companies. It contains the above listed commodities with a variety of attribution. This dataset is on ongoing project. For access to the more comprehensive pipeline database call the Wyoming Pipeline Authority at 307-237-5009.",
        metaURL:"<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid=%7b29BE6E5E-C16B-48C2-861D-188AFE007306%7d' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='https://www.wyopipeline.com/' target='_blank'>Wyoming Pipeline Authority Website</a>"}, 
     {
        name: "Condensate",
         shortDescription: "This dataset consists of a statewide GIS database of major oil, gas, carbon dioxide, water, and product pipelines for the state of Wyoming.",
        longDescription: "This dataset consists of a statewide GIS database of major oil, gas, carbon dioxide, water, and product pipelines for the state of Wyoming. It was produced by the Wyoming Pipeline Authority with an initial contribution by the Wyoming State Geological Survey and the help of various companies. It contains the above listed commodities with a variety of attribution. This dataset is on ongoing project. For access to the more comprehensive pipeline database call the Wyoming Pipeline Authority at 307-237-5009.",
        metaURL:"<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid=%7b29BE6E5E-C16B-48C2-861D-188AFE007306%7d' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='https://www.wyopipeline.com/' target='_blank'>Wyoming Pipeline Authority Website</a>"}, 
     {
        name: "Product",
         shortDescription: "This dataset consists of a statewide GIS database of major oil, gas, carbon dioxide, water, and product pipelines for the state of Wyoming.",
        longDescription: "This dataset consists of a statewide GIS database of major oil, gas, carbon dioxide, water, and product pipelines for the state of Wyoming. It was produced by the Wyoming Pipeline Authority with an initial contribution by the Wyoming State Geological Survey and the help of various companies. It contains the above listed commodities with a variety of attribution. This dataset is on ongoing project. For access to the more comprehensive pipeline database call the Wyoming Pipeline Authority at 307-237-5009.",
        metaURL:"<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid=%7b29BE6E5E-C16B-48C2-861D-188AFE007306%7d' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='https://www.wyopipeline.com/' target='_blank'>Wyoming Pipeline Authority Website</a>"}, 
     {
        name: "Natural Gas Liquid",
        shortDescription: "This dataset consists of a statewide GIS database of major oil, gas, carbon dioxide, water, and product pipelines for the state of Wyoming.",
        longDescription: "This dataset consists of a statewide GIS database of major oil, gas, carbon dioxide, water, and product pipelines for the state of Wyoming. It was produced by the Wyoming Pipeline Authority with an initial contribution by the Wyoming State Geological Survey and the help of various companies. It contains the above listed commodities with a variety of attribution. This dataset is on ongoing project. For access to the more comprehensive pipeline database call the Wyoming Pipeline Authority at 307-237-5009.",
        metaURL:"<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid=%7b29BE6E5E-C16B-48C2-861D-188AFE007306%7d' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='https://www.wyopipeline.com/' target='_blank'>Wyoming Pipeline Authority Website</a>"}, 
     {
        name: "Crude",
         shortDescription: "This dataset consists of a statewide GIS database of major oil, gas, carbon dioxide, water, and product pipelines for the state of Wyoming.",
        longDescription: "This dataset consists of a statewide GIS database of major oil, gas, carbon dioxide, water, and product pipelines for the state of Wyoming. It was produced by the Wyoming Pipeline Authority with an initial contribution by the Wyoming State Geological Survey and the help of various companies. It contains the above listed commodities with a variety of attribution. This dataset is on ongoing project. For access to the more comprehensive pipeline database call the Wyoming Pipeline Authority at 307-237-5009.",
        metaURL:"<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid=%7b29BE6E5E-C16B-48C2-861D-188AFE007306%7d' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='https://www.wyopipeline.com/' target='_blank'>Wyoming Pipeline Authority Website</a>"}, 
     {
        name: "Natural Gas",
         shortDescription: "This dataset consists of a statewide GIS database of major oil, gas, carbon dioxide, water, and product pipelines for the state of Wyoming.",
        longDescription: "This dataset consists of a statewide GIS database of major oil, gas, carbon dioxide, water, and product pipelines for the state of Wyoming. It was produced by the Wyoming Pipeline Authority with an initial contribution by the Wyoming State Geological Survey and the help of various companies. It contains the above listed commodities with a variety of attribution. This dataset is on ongoing project. For access to the more comprehensive pipeline database call the Wyoming Pipeline Authority at 307-237-5009.",
        metaURL:"<a href='http://explorer.geospatialhub.org/geoportal/catalog/search/resource/details.page?uuid=%7b29BE6E5E-C16B-48C2-861D-188AFE007306%7d' target='_blank'>Full Metadata Record</a>",
        detailsURL: "<a href='https://www.wyopipeline.com/' target='_blank'>Wyoming Pipeline Authority Website</a>"},
    {
        name: "2D Seismic",
         shortDescription: "This dataset consists of a statewide GIS  2D and 3D seismic library.",
        longDescription: "This dataset consists of a statewide GIS  2D and 3D seismic library.",
        metaURL:"<a href='http://www.seismicexchange.com/seismic_library/our_library_overview' target='_blank'>Data Source</a>",
        detailsURL: "<a href='http://www.seismicexchange.com/' target='_blank'>Seismic Exchange, Inc. (SEI)</a>"},
    {
        name: "3D Seismic",
         shortDescription: "This dataset consists of a statewide GIS  2D and 3D seismic library.",
        longDescription: "This dataset consists of a statewide GIS  2D and 3D seismic library.",
        metaURL:"<a href='http://www.seismicexchange.com/seismic_library/our_library_overview' target='_blank'>Data Source</a>",
        detailsURL: "<a href='https://www.wyopipeline.com/' target='_blank'>Seismic Exchange, Inc. (SEI)</a>"}
     
];

